author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
description: SpleefLeague Core Plugin
main: com.spleefleague.core.SpleefLeague
name: SpleefLeagueCore
url: http://www.spleefleague.com/
version: 1.1
softdepend: [ProtocolLib]
loadbefore: [Commands, SuperJump, SuperSpleef]